version: "3"
services:
  ds-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - JUPYTER_ENABLE_LAB=yes
        - JUPYTER_TOKEN=vp

    volumes:
        - ./work:/home/jovyan/work
    ports:
      - "8888:8888"