version: "3"
services:
  ds-notebook:
    build:
      context: .
    #image: jupyter/scipy-notebook
    environment:
        - JUPYTER_ENABLE_LAB=yes

    volumes:
        - ./:/home/jovyan/
    ports:
      - "8888:8888"